### Put a value
PUT http://c6-9.ifi.uit.no:33129/storage/missing-key
Content-Type: text/plain

hello world

### Get the value (should return "hello world")
GET http://c6-9.ifi.uit.no:33129/storage/abc123

### Get a missing value (should return 404)
GET http://c6-9.ifi.uit.no:33129/storage/missing-key

### Get network info
GET http://c6-9.ifi.uit.no:33129/network
