### Put a value
PUT http://c11-14.ifi.uit.no:38865/storage/missing-key
Content-Type: text/plain

hello world

### Get the value (should return "hello world")
GET http://c11-14.ifi.uit.no:38865/storage/abc123

### Get a missing value (should return 404)
GET http://c11-14.ifi.uit.no:38865/storage/missing-key

### Get network info
GET http://c11-14.ifi.uit.no:38865/network
